# using py format for comments, which is not allowed in json

text = "" 
emoji = ""
date = ""
time = ""

# in the following dicts, all list means multi choice, the value shoule be one of the element in []

# user input format
{
    "date": date, # date of the communication
    "time": time, # time of the communication
    "type": [
        "talking",
        "feeding",
        "petting"
    ],
    "text": [
        None,
        text
    ] # the text input from user if type is talking, otherwise will be null.
}

# GPT response format
{
    "info": {
        "date": date, # date of the communication
        "time": time, # time of the communication
        "loc": [
            "bedroom",
            "living room",
            "washing room"
        ] # location of the pet at the input time
    },
    "communication": {
        "text": [
            None,
            text
        ], # the text output from assistant, can be null if there is no text
        "animation": [
            None,
            "greeting",
            "ask for food",
            "response to user",
            "conversation",
            "using toilet",
            "eating & drinkng",
            "playing"
        ], # the token of animation generated by assistant, can be null if there is no suitable animation
        "emoji": [
            None,
            emoji
        ] # the emoji generated by assistant, will be null if there is no suitable emoji
    }
}


# user input example
{
    "date": "2023/06/06",
    "time": "16:21",
    "type": "talking",
    "text": "Hi! Long time no see! I miss you so much!"
}